sonar.host.url=http://10.0.2.15:9000
sonar.projectName=java-application
sonar.projectKey=java-application
sonar.sources=src/main
sonar.cs.opencover.reportsPaths="**/build/test-results/test/*.xml"
sonar.buildString=Release-1.0.0
sonar.java.binaries=build-artefact/build/classes/java/main
sonar.tests=src/test
sonar.verbose=true
sonar.qualitygate.wait=true