spring:
  application:
    name: env-printer-springboot

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  runtime-env-name: APP_RUNTIME_VALUE
