name: AWS Runner 
run-name: ${{ github.ref_name }}.${{ github.run_number }}

on:
  # push:
  #   branches:
  #     - main
  #     - 'release/**'
  workflow_dispatch:

jobs:
  build:
    name: '-'
    uses: frankbuttigieg1993-gmail/cicd/.github/workflows/aws-runner.yml@main
    permissions:
      id-token: write
      contents: write 
      security-events: write
      actions: write
    secrets:
      AWS_GITHUB_RUNNER_TOKEN: ${{ secrets.AWS_GITHUB_RUNNER_TOKEN }} # Map the actual secret to the input key
      AWS_GITHUB_ACCESS_KEY_ID: ${{ secrets.AWS_GITHUB_ACCESS_KEY_ID }}
      AWS_GITHUB_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_GITHUB_SECRET_ACCESS_KEY_ID }}
# secrets: inherit
