name: Build Code Quality Pipeline
run-name: ${{ github.ref_name }}.${{ github.run_number }}

on:
  push:
    branches:
      - main
      - 'release/**'
  workflow_dispatch:

jobs:
  build:
    name: '-'
    uses: frankbuttigieg1993-gmail/cicd/.github/workflows/java-build-selfhosted-scanning.yml@main
    permissions:
      id-token: write
      contents: write 
      security-events: write
      actions: read
    with:
      target-runner: "['self-hosted', 'linux', 'x64']"
    secrets: inherit
### TODO - Look up Secret Inheritence