name: Dev Deployment Pipeline
run-name: ${{ inputs.docker_tag }}


on:
  # push:
  #   branches:
  #     - main
  #     - 'release/**'
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker image tag to deploy'
        required: true
        default: '1.0.0.53'
jobs:
  Deploy:
    name: '-'
    uses: frankbuttigieg1993-gmail/cicd/.github/workflows/Java-Deployment-Dev.yaml@main
    permissions:
      id-token: write
      contents: write 
    secrets:
      GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }} # Map the actual secret to the input key
      GH_PRIVATE_SSH_KEY: ${{ secrets.GH_PRIVATE_SSH_KEY }}
