name: PR Pipeline
run-name: PR-${{ github.event.pull_request.number }}-${{ github.event.pull_request.title }}

on:
  pull_request:
    branches: [ release/* ]
  workflow_dispatch:

jobs:
  build:
    name: '-'
    uses: frankbuttigieg1993-gmail/cicd/.github/workflows/java-build-pr.yml@main
    permissions:
      id-token: write
      contents: write 
      security-events: write
    with:
      target-runner: "['self-hosted', 'linux', 'x64']"
    
